### ISSUE TITLE
Mapnik server can crash

### ISSUE THREAD

**Issue by MattBlissett** [gbif/maps#65]
The server crashes after this exception: 

```
Trace: Error: end of buffer exception
    at renderTile (/usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:31:6)
    at /usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:77:31
    at /usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1135:9
    at eachOfArrayLike (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1069:9)
    at eachOf (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1133:5)
    at Object.map (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1122:16)
    at heatMapRender (/usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:76:9)
    at module.exports (/usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:148:5)
    at /usr/local/gbif/services/mapnik-server/0.32/1654094130/server.js:54:13
    at process.<anonymous> (/usr/local/gbif/services/mapnik-server/0.32/1654094130/server.js:149:13)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
Trace: Error: end of buffer exception
    at renderTile (/usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:31:6)
    at /usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:77:31
    at /usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1135:9
    at eachOfArrayLike (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1069:9)
    at eachOf (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1133:5)
    at Object.map (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1122:16)
    at heatMapRender (/usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:76:9)
    at module.exports (/usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:148:5)
    at /usr/local/gbif/services/mapnik-server/0.32/1654094130/server.js:54:13
    at process.<anonymous> (/usr/local/gbif/services/mapnik-server/0.32/1654094130/server.js:149:13)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
```

**Comment by MattBlissett** [comment]
Fixed in dd0cfdc525e01aaacc7a653708bbfdf092706246

**Comment by MattBlissett** [comment]
```
(node:15614) Warning: No such label 'Get http://api.gbif.org:80/v2/map/occurrence/density/4/15/3.mvt?bin=hex&hexPerTile=15&taxonKey=5299694&srs=EPSG%3A4326' for console.timeEnd()
(node:15614) Warning: No such label 'Get http://api.gbif.org:80/v2/map/occurrence/density/4/17/3.mvt?bin=hex&hexPerTile=15&taxonKey=5299694&srs=EPSG%3A4326' for console.timeEnd()
Trace: Error: end of buffer exception
    at renderTile (/usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:31:6)
    at /usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:77:31
    at /usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1135:9
    at eachOfArrayLike (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1069:9)
    at eachOf (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1133:5)
    at Object.map (/usr/local/gbif/services/mapnik-server/0.32/1654094130/node_modules/async/dist/async.js:1122:16)
    at heatMapRender (/usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:76:9)
    at module.exports (/usr/local/gbif/services/mapnik-server/0.32/1654094130/renderer.js:148:5)
    at /usr/local/gbif/services/mapnik-server/0.32/1654094130/server.js:55:15
    at process.<anonymous> (/usr/local/gbif/services/mapnik-server/0.32/1654094130/server.js:161:13)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
```

Hmm.

**Comment by MattBlissett** [comment]
Again:

```
Trace: Error: end of buffer exception
    at renderTile (/usr/local/gbif/services/mapnik-server/0.35/1679409013/renderer.js:31:6)
    at /usr/local/gbif/services/mapnik-server/0.35/1679409013/renderer.js:77:31
    at /usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1135:9
    at eachOfArrayLike (/usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1069:9)
    at eachOf (/usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1133:5)
    at Object.map (/usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1122:16)
    at heatMapRender (/usr/local/gbif/services/mapnik-server/0.35/1679409013/renderer.js:76:9)
    at module.exports (/usr/local/gbif/services/mapnik-server/0.35/1679409013/renderer.js:148:5)
    at /usr/local/gbif/services/mapnik-server/0.35/1679409013/server.js:55:15
    at process.<anonymous> (/usr/local/gbif/services/mapnik-server/0.35/1679409013/server.js:161:13)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
Trace: Error: end of buffer exception
    at renderTile (/usr/local/gbif/services/mapnik-server/0.35/1679409013/renderer.js:31:6)
    at /usr/local/gbif/services/mapnik-server/0.35/1679409013/renderer.js:77:31
    at /usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1135:9
    at eachOfArrayLike (/usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1069:9)
    at eachOf (/usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1117:5)
    at _asyncMap (/usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1133:5)
    at Object.map (/usr/local/gbif/services/mapnik-server/0.35/1679409013/node_modules/async/dist/async.js:1122:16)
    at heatMapRender (/usr/local/gbif/services/mapnik-server/0.35/1679409013/renderer.js:76:9)
    at module.exports (/usr/local/gbif/services/mapnik-server/0.35/1679409013/renderer.js:148:5)
    at /usr/local/gbif/services/mapnik-server/0.35/1679409013/server.js:55:15
    at process.<anonymous> (/usr/local/gbif/services/mapnik-server/0.35/1679409013/server.js:161:13)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
```

**Comment by MortenHofft** [comment]
I've tried to fix it by a try catch in the server file. 

We could also have looked at fixing it closer to the source in `renderer.js`. Two places stand out to me as odd at first glance, but there might be a reason it is done like this. It does look odd though:

https://github.com/gbif/maps/blob/20c3e7d2cbb64b83d8048edb9707af64b6f00be8/mapnik-server/src/main/node/renderer.js#L79
There might be good reasons why we continue despite errors (perhaps tiles outside boundaries or empty tiles are considered errors at this point and handled somehow subsequently)

Similarly this looks odd https://github.com/gbif/maps/blob/20c3e7d2cbb64b83d8048edb9707af64b6f00be8/mapnik-server/src/main/node/renderer.js#L63
If there is an error, then encode the result as a png?
